name: wallet
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  ffi: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.forbole.wallet
        pluginClass: WalletPlugin
      ios:
        pluginClass: WalletPlugin
      linux:
        pluginClass: WalletPlugin
      macos:
        pluginClass: WalletPlugin
      windows:
        pluginClass: WalletPlugin
      web:
        pluginClass: WalletWeb
        fileName: wallet_web.dart
