[package]
name = "wallet_ffi"
version = "0.1.0"
edition = "2018"

[lib]
name = "wallet_ffi"
crate-type = ["rlib"]

[dependencies]
wallet = { path = "../wallet" }
libc = "0.2.92"

[build-dependencies]
cbindgen = "0.14.3"
dart-bindgen = "0.1.7"
